import Header from '@/components/Header'
import './globals.css'

export const metadata = {
  title: 'Blog MERN',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="es">
      <body className='bg-[#111827] text-white w-[400px] md:w-[750px] max-w-[400px] md:max-w-[800px] m-auto'>
        <Header/>
        {children}
      </body>
    </html>
  )
}
